x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  # The images property will be filled in during part 2
  images:
    '':
      properties:
        reportportal.serviceapi.repository:
          type: REPO_WITH_REGISTRY
        reportportal.serviceapi.tag:
          type: TAG
    reportportal-index:
      properties:
        reportportal.serviceindex.repository:
          type: REPO_WITH_REGISTRY
        reportportal.serviceindex.tag:
          type: TAG
    reportportal-ui:
      properties:
        reportportal.serviceui.repository:
          type: REPO_WITH_REGISTRY
        reportportal.serviceui.tag:
          type: TAG
    reportportal-uat:
      properties:
        reportportal.uat.repository:
          type: REPO_WITH_REGISTRY
        reportportal.uat.tag:
          type: TAG
    reportportal-jobs:
      properties:
        reportportal.servicejobs.repository:
          type: REPO_WITH_REGISTRY
        reportportal.servicejobs.tag:
          type: TAG
    reportportal-analyzer:
      properties:
        reportportal.serviceanalyzer.repository:
          type: REPO_WITH_REGISTRY
        reportportal.serviceanalyzer.tag:
          type: TAG
    reportportal-metricsgatherer:
      properties:
        reportportal.metricsgatherer.repository:
          type: REPO_WITH_REGISTRY
        reportportal.metricsgatherer.tag:
          type: TAG
    reportportal-migrations:
      properties:
        reportportal.migrations.repository:
          type: REPO_WITH_REGISTRY
        reportportal.migrations.tag:
          type: TAG
    postgresql-11:
      properties:
        reportportal.postgresql.image.registry:
          type: REGISTRY
        reportportal.postgresql.image.repository:
          type: REPO_WITHOUT_REGISTRY
        reportportal.postgresql.image.tag:
          type: TAG 
    rabbitmq-3:
      properties:
        reportportal.rabbitmq.image.registry:
          type: REGISTRY
        reportportal.rabbitmq.image.repository:
          type: REPO_WITHOUT_REGISTRY
        reportportal.rabbitmq.image.tag:
          type: TAG
    opensearch-2:
      properties:
        reportportal.opensearch.image.repository:
          type: REPO_WITH_REGISTRY
        reportportal.opensearch.image.tag:
          type: TAG
    minio-2021:
      properties:
        reportportal.minio.image.registry:
          type: REGISTRY
        reportportal.minio.image.repository:
          type: REPO_WITHOUT_REGISTRY
        reportportal.minio.image.tag:
          type: TAG

properties:
  name:
    type: string
    default: reportportal
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: reportportal
    x-google-marketplace:
      type: NAMESPACE
  reportportal.uat.superadminInitPasswd.password:
    title: Superadmin Initial Password
    type: string
    description: The initial password for the superadmin user.
    default: admin
    x-google-marketplace:
      type: MASKED_FIELD
  reportportal.serviceAccount.name:
    title: Service Account Name
    type: string
    description: The name of the service account to create.
    default: reportportal
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: The service account for handling deploy sequence.
        roles:
        - type: Role
          rulesType: CUSTOM        # We specify our own custom RBAC rules
          rules:
          - apiGroups: ["", "batch"]
            resources: ["pods","services", "jobs"]
            verbs: ["get", "list", "watch"]

required:
- name
- namespace
- reportportal.uat.superadminInitPasswd.password
