x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '0.1.0'
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  # The images property will be filled in during part 2
  images: {}

properties:
  name:
    type: string
    default: reportportal
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    default: reportportal
    x-google-marketplace:
      type: NAMESPACE
  uat.superadminInitPasswd.password:
    title: Superadmin Initial Password
    type: string
    default: erebus
    description: The initial password for the superadmin user.
    x-google-marketplace:
      type: MASKED_FIELD
  rbac.serviceAccount.name:
    title: Service Account Name
    type: string
    description: The name of the service account to create.
    default: reportportal
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: The service account for handling deploy sequence.
        roles:
        - type: Role               # This is a namespaced Role
          rulesType: CUSTOM        # We specify our own custom RBAC rules
          rules:
          - apiGroups: ["", "batch"]
            resources: ["pods","services", "jobs"]
            verbs: ["get", "list", "watch"]
required:
- name
- namespace
- uat.superadminInitPasswd.password